feature_set: default
dataset: db1
models:
- lda
normalizer: standard
feat_select: none
timestamp: '2025-12-24T15:38:45.006102'
k: 50
pca_n: 50
subsample_frac: 0.1
dataset_info:
  n_samples: 5470
  n_features: 165
  n_subjects: 3
  n_classes: 52
  subjects:
  - s01
  - s02
  - s03
