feature_set: preproc_highpass_30_500
dataset: db1
models:
- lda
normalizer: standard
feat_select: none
timestamp: '2025-12-30T20:43:09.937231'
k: 50
pca_n: 50
subsample_frac: 0.5
feature_subdir: default/preproc_highpass_30_500
dataset_info:
  n_samples: 261726
  n_features: 165
  n_subjects: 27
  n_classes: 52
  subjects:
  - s01
  - s02
  - s03
  - s04
  - s05
  - s06
  - s07
  - s08
  - s09
  - s10
  - s11
  - s12
  - s13
  - s14
  - s15
  - s16
  - s17
  - s18
  - s19
  - s20
  - s21
  - s22
  - s23
  - s24
  - s25
  - s26
  - s27
