feature_set: default
dataset: rami
models:
- et-tuned
normalizer: standard
feat_select: none
timestamp: '2025-12-24T16:57:35.588659'
k: 50
pca_n: 50
subsample_frac: 0.1
feature_subdir: combined/all
dataset_info:
  n_samples: 24600
  n_features: 105
  n_subjects: 5
  n_classes: 8
  subjects:
  - s01
  - s02
  - s03
  - s04
  - s05
