feature_set: preproc_no_preprocessing
dataset: myo
models:
- lda
normalizer: standard
feat_select: none
timestamp: '2025-12-25T22:52:24.267767'
k: 50
pca_n: 50
feature_subdir: default/preproc_no_preprocessing
dataset_info:
  n_samples: 1182027
  n_features: 312
  n_subjects: 43
  n_classes: 17
  subjects:
  - s01
  - s02
  - s03
  - s04
  - s05
  - s06
  - s07
  - s08
  - s09
  - s10
  - s11
  - s12
  - s13
  - s14
  - s15
  - s16
  - s17
  - s18
  - s19
  - s20
  - s21
  - s22
  - s23
  - s24
  - s25
  - s26
  - s27
  - s28
  - s29
  - s30
  - s31
  - s32
  - s33
  - s34
  - s35
  - s36
  - s37
  - s38
  - s39
  - s40
  - s41
  - s42
  - s43
