feature_set: default
dataset: db1
models:
- et-tuned
normalizer: standard
feat_select: none
timestamp: '2025-12-24T22:09:51.372850'
k: 50
pca_n: 50
calibration_samples: 10
subsample_frac: 0.1
feature_subdir: combined/all
dataset_info:
  n_samples: 51733
  n_features: 165
  n_subjects: 27
  n_classes: 52
  subjects:
  - s01
  - s02
  - s03
  - s04
  - s05
  - s06
  - s07
  - s08
  - s09
  - s10
  - s11
  - s12
  - s13
  - s14
  - s15
  - s16
  - s17
  - s18
  - s19
  - s20
  - s21
  - s22
  - s23
  - s24
  - s25
  - s26
  - s27
